name: sample-ws
services:
- name: client-ws
  github:
    repo: bojand/sample-ws
    branch: main
  run_command: node client/index.js
  envs:
  - key: WS_LOCATION
    value: ${APP_DOMAIN}
    scope: RUN_TIME
  - key: WS_PORT
    value: ${server.PRIVATE_PORT}
    scope: RUN_TIME
- name: server
  github:
    repo: bojand/sample-ws
    branch: main
  run_command: node server/index.js
  routes:
  - path: /api