name: sample-socketio
services:
- name: server
  github:
    repo: bojand/sample-ws
    branch: socketio
  run_command: node index.js
  envs:
  - key: WS_HOST
    scope: RUN_TIME
    value: ${server.PUBLIC_URL}
  - key: NODE_ENV
    scope: RUN_TIME
    value: production